create table address (id bigint generated by default as identity, street varchar(255), city varchar(100), state varchar(100), zip varchar(12), primary key (id));

create table contact_name (id bigint generated by default as identity, first_name varchar(60), middle_name varchar(60), last_name varchar(60), primary key (id));

create table contact (id bigint generated by default as identity, contact_name_id bigint, address_id bigint, email varchar(100), primary key (id));

alter table contact add constraint FKcaf6ht0hfw93lwc13ny0sdmvo foreign key (address_id) references address(id);

alter table contact add constraint FKcaf6ht0hfw93lwc13ny0sdmvw foreign key (contact_name_id) references contact_name(id);

create table phone_number (id bigint generated by default as identity, number varchar(20), type varchar(15), contact_id bigint, primary key (id));

alter table phone_number add constraint FK_contact foreign key (contact_id) references contact(id);
